/**
 * FAQ statiche di sistema (audience PUBLIC/ADMIN/OPERATOR).
 * Vengono usate come fallback se il DB non ha FAQ caricate per quel tenant.
 */
export type StaticFaq = { id: string; category: string; question: string; answer: string; audience: "ADMIN" | "OPERATOR" | "CUSTOMER" | "PUBLIC"; tags: string[] };

export const STATIC_FAQS: StaticFaq[] = [
  // ADMIN
  { id: "f-admin-1", category: "Anagrafiche", audience: "ADMIN", tags: ["clienti", "import"],
    question: "Come importo clienti in massa da Excel?",
    answer: "Dalla pagina Clienti, attualmente il bulk import passa via API. Puoi: (1) usare l'endpoint POST /api/customers ripetuto con uno script, (2) usare l'export CSV come template e attendere la funzionalità UI di import (roadmap v2). Per import grossi (>500 clienti) chiedi a noi: facciamo un'importazione one-shot dal vecchio gestionale (TeamSystem, Edison, Perfetto, etc)." },
  { id: "f-admin-2", category: "Fatturazione", audience: "ADMIN", tags: ["sdi", "xml", "fatturapa"],
    question: "Come funziona l'invio fatture al SDI?",
    answer: "Ampera genera l'XML FatturaPA 1.9.1 conforme. Dall'app fattura tap 'XML SDI' per scaricare il file da inviare. Per l'invio diretto al SDI serve un intermediario accreditato (Aruba, Infocert, Register.it). L'integrazione diretta è in roadmap v2; nel frattempo l'XML è pronto per l'upload manuale sul portale del tuo intermediario." },
  { id: "f-admin-3", category: "Fatturazione", audience: "ADMIN", tags: ["iva", "aliquota"],
    question: "Posso usare IVA differenziate nella stessa fattura?",
    answer: "Sì. Ogni riga ha la sua aliquota IVA. Tipici scenari: 10% per opere su ristrutturazione/manutenzione edilizia (DPR 633/72 tab. A parte III), 22% per nuovo impianto, 4% per accessibilità (legge 104). I totali nei riepiloghi vengono divisi per aliquota automaticamente." },
  { id: "f-admin-4", category: "Fatturazione", audience: "ADMIN", tags: ["sconto", "scontistica"],
    question: "Come applico sconti per riga o totale?",
    answer: "Hai due opzioni: (1) sconto per riga in % o in € (campo dedicato), (2) sconto globale % sull'imponibile. Puoi anche combinarli: sconto per riga (es. promozione articolo) + sconto globale (es. cliente fedele -5%). L'XML SDI esporta correttamente ScontoMaggiorazione." },
  { id: "f-admin-5", category: "Fatturazione", audience: "ADMIN", tags: ["reverse charge", "edilizia"],
    question: "Quando applicare reverse charge edilizia?",
    answer: "Per appalti e subappalti nel settore edile tra soggetti IVA (art. 17 c. 6 lett. a) DPR 633/72). Spunta 'Reverse charge' nella creazione fattura: la riga avrà nota normativa automatica e l'IVA NON sarà esposta. Il cliente versa l'IVA in autoliquidazione." },
  { id: "f-admin-6", category: "Fatturazione", audience: "ADMIN", tags: ["split", "pa"],
    question: "Come gestisco split payment per PA?",
    answer: "Per fatture a Pubblica Amministrazione (cliente tipo PUBLIC_ADMIN): spunta 'Split payment'. L'IVA non viene incassata da te ma versata direttamente dalla PA all'erario. Esigibilità IVA = S nell'XML SDI." },
  { id: "f-admin-7", category: "Fatturazione", audience: "ADMIN", tags: ["bollo"],
    question: "Quando aggiungere il bollo virtuale?",
    answer: "Per fatture senza IVA (esempio: regime forfettario o operazioni esenti) con importo > €77,47 serve bollo da 2€. Inserisci 2.00 nel campo 'Bollo €' alla creazione fattura. Per fatture elettroniche l'imposta è virtuale (DPR 642/72)." },
  { id: "f-admin-8", category: "Preventivi", audience: "ADMIN", tags: ["versioning"],
    question: "Posso modificare un preventivo già inviato?",
    answer: "Sì creando una versione v2, v3, etc. Il sistema mantiene tutte le versioni e traccia lo storico delle modifiche. L'ultima accettata diventa quella di riferimento per conversione in fattura." },
  { id: "f-admin-9", category: "Rapportini", audience: "ADMIN", tags: ["modifica", "immutable"],
    question: "Come modifico un rapportino già firmato?",
    answer: "I rapportini firmati (status SUBMITTED) sono immutable per audit-trail conformità. Per correzioni: (1) crea rapportino integrativo collegato allo stesso intervento, oppure (2) annulla la fattura con nota credito e re-emetti. Non si modifica MAI un documento firmato dal cliente." },
  { id: "f-admin-10", category: "DICO", audience: "ADMIN", tags: ["dm 37/08", "conformita"],
    question: "Quali allegati servono per una DICO completa?",
    answer: "Per DM 37/08: (1) Progetto firmato dal RT (se obbligatorio per tipologia), (2) Relazione dei materiali utilizzati, (3) Schema dell'impianto realizzato, (4) Riferimento dichiarazioni di conformità prodotti, (5) Copia visura camerale ditta installatrice. Senza questi la DICO è 'incompleta' e non rispetta DM 37/08." },
  { id: "f-admin-11", category: "Sicurezza", audience: "ADMIN", tags: ["2fa", "password"],
    question: "Come attivo l'autenticazione 2FA?",
    answer: "Vai in Impostazioni → Sicurezza → Configura TOTP. Scansiona il QR code con Google Authenticator o Aegis. Il codice viene richiesto a ogni login successivo. Obbligatorio per ruoli OWNER e ADMIN dalla v2." },
  { id: "f-admin-12", category: "Magazzino", audience: "ADMIN", tags: ["van", "furgone"],
    question: "Come gestisco il magazzino di un furgone?",
    answer: "Vai in Magazzino → Nuovo magazzino → tipo VAN, assegna il tecnico. Da quel momento, quando il tecnico chiude un rapportino i materiali vengono scaricati automaticamente dal suo furgone. Riassortimento con movimento TRANSFER da HQ." },
  { id: "f-admin-13", category: "Agevolazioni", audience: "ADMIN", tags: ["50%", "ristrutturazione"],
    question: "Come funziona il Bonus Ristrutturazioni 50%?",
    answer: "Art. 16-bis TUIR: detrazione IRPEF del 50% delle spese sostenute fino a €96.000 per unità immobiliare, recupero in 10 anni. Documenti necessari: bonifico parlante con causale 'art. 16-bis TUIR DPR 917/86', fatture con dicitura specifica, dati catastali immobile. Ampera genera tutto auto-compilato in Agevolazioni → Nuova pratica." },
  { id: "f-admin-14", category: "Agevolazioni", audience: "ADMIN", tags: ["enea", "ecobonus"],
    question: "Quando devo inviare comunicazione ENEA?",
    answer: "Entro 90 giorni dalla fine dei lavori per: (1) Ecobonus 65%, (2) Detrazione 50% se include risparmio energetico (es. infissi, schermature), (3) Bonus Mobili per elettrodomestici classe energetica indicata. La pagina Agevolazioni ti avvisa con countdown e ti compila il modulo ENEA." },
  { id: "f-admin-15", category: "Privacy", audience: "ADMIN", tags: ["gdpr", "informativa"],
    question: "Devo dare informativa privacy al cliente?",
    answer: "Sì, art. 13 GDPR. Ampera ha modelli pronti in Privacy → Informativa cliente. Stampa, fai firmare al primo contatto e archivia. Il consenso è tracciato con data, IP e user-agent." },

  // OPERATOR
  { id: "f-op-1", category: "Rapportino", audience: "OPERATOR", tags: ["voce", "dettatura"],
    question: "Come uso la dettatura vocale?",
    answer: "Nello step 3 (Descrizione) tap il microfono in basso a destra. Parla normalmente in italiano: il testo appare mentre parli. Per ri-iniziare tocca di nuovo il microfono. Funziona su Chrome/Edge/Safari di iPhone." },
  { id: "f-op-2", category: "Rapportino", audience: "OPERATOR", tags: ["offline"],
    question: "Cosa succede se non ho campo?",
    answer: "Tutto continua a funzionare. Il rapportino viene salvato in locale. Quando torni in copertura sincronizza in automatico (vedi notifica). Foto, firma e materiali: tutto preservato." },
  { id: "f-op-3", category: "Rapportino", audience: "OPERATOR", tags: ["foto", "gps"],
    question: "Le foto sono geo-localizzate?",
    answer: "Sì, automaticamente se hai dato permesso GPS. Coordinate salvate insieme alla foto: prova certifica intervento e luogo. Le foto vengono anche compresse a max 1280px per veloce upload anche con linea lenta." },
  { id: "f-op-4", category: "Rapportino", audience: "OPERATOR", tags: ["firma"],
    question: "Come faccio firmare il cliente?",
    answer: "Step 6: tap area firma. Si apre canvas fullscreen. Passa lo smartphone al cliente che firma con il dito. Tap 'Usa firma' per confermare. Firma salvata in PNG vettoriale con timestamp." },
  { id: "f-op-5", category: "Rapportino", audience: "OPERATOR", tags: ["barcode"],
    question: "Posso aggiungere materiali con il barcode?",
    answer: "Sì: step 5 → tap barra di ricerca → tap icona barcode (in roadmap v2 PWA full). Per ora ricerca testuale rapida e materiali recenti. Standard codice METEL supportato." },
  { id: "f-op-6", category: "Generale", audience: "OPERATOR", tags: ["installazione", "pwa"],
    question: "Come installo l'app sul telefono?",
    answer: "Apri ampera.isipc.com/operatore in Chrome (Android) o Safari (iPhone). Tap 'Aggiungi a schermata Home'. Diventa un'icona come app nativa. Funziona anche offline." },
  { id: "f-op-7", category: "Generale", audience: "OPERATOR", tags: ["timbratura"],
    question: "Devo timbrare ogni mattina?",
    answer: "Consigliato per tracciare orario di inizio giornata e posizione GPS. Tap 'Inizia giornata' nella home. Non bloccante: puoi comunque aprire interventi e compilare rapportini senza timbrare." },

  // CUSTOMER (portale)
  { id: "f-cli-1", category: "Generale", audience: "CUSTOMER", tags: ["preventivo"],
    question: "Come accetto un preventivo?",
    answer: "Hai ricevuto un'email con il link al preventivo? Tap il link, leggi il documento, scendi in fondo, firma con il dito o mouse. Riceverai conferma email. Il preventivo accettato vincola lo stato 'ordinato' e sblocca la programmazione lavori." },
  { id: "f-cli-2", category: "Generale", audience: "CUSTOMER", tags: ["fattura"],
    question: "Come ricevo le fatture?",
    answer: "Le fatture vengono inviate al SDI verso il tuo codice destinatario o PEC. Le ricevi tramite il tuo cassetto fiscale o il tuo commercialista. Puoi anche vederle nel portale cliente quando attivo." },

  // PUBLIC
  { id: "f-pub-1", category: "Ampera", audience: "PUBLIC", tags: ["chi siamo"],
    question: "Cos'è Ampera?",
    answer: "Ampera è il CRM/gestionale verticale per aziende italiane di impianti elettrici. Tutto quello che serve: clienti, impianti, preventivi, rapportini mobile, DICO, fatturazione SDI, magazzino. Cloud o self-hosted Coolify." },
  { id: "f-pub-2", category: "Ampera", audience: "PUBLIC", tags: ["pricing", "prezzo"],
    question: "Quanto costa?",
    answer: "Free per artigiano singolo (1 utente, 10 commesse/mese). Starter 19€/utente/mese (multi-utente). Pro 29€/u/m (DICO automatica + portale cliente). Business 49€/u/m (AI avanzata + API). Self-hosted 3000€/anno." },
  { id: "f-pub-3", category: "Tecnico", audience: "PUBLIC", tags: ["dati", "sicurezza"],
    question: "Dove sono salvati i miei dati?",
    answer: "Server in Italia (Veneto). Backup giornaliero retention 30 giorni. Crittografia AES-256-GCM at-rest per dati sensibili. SSL Let's Encrypt. Conforme GDPR. Per chi vuole massima sovranità: deploy self-hosted sul tuo server con Coolify." },
];
