-- v7: GIN FTS indexes (italian) per ricerca full-text per-tabella
-- Espressione tsvector identica a buildTsVectorExpr() in src/lib/search-fields.ts

CREATE INDEX IF NOT EXISTS "customer_fts_idx" ON "Customer" USING GIN (to_tsvector('italian', coalesce(name,'') || ' ' || coalesce(surname,'') || ' ' || coalesce("companyName",'') || ' ' || coalesce("vatNumber",'') || ' ' || coalesce("fiscalCode",'') || ' ' || coalesce(email,'') || ' ' || coalesce(phone,'') || ' ' || coalesce(mobile,'') || ' ' || coalesce("sdiCode",'') || ' ' || coalesce(pec,'') || ' ' || coalesce(notes,'')));
CREATE INDEX IF NOT EXISTS "supplier_fts_idx" ON "Supplier" USING GIN (to_tsvector('italian', coalesce(name,'') || ' ' || coalesce("vatNumber",'') || ' ' || coalesce("fiscalCode",'') || ' ' || coalesce(email,'') || ' ' || coalesce(phone,'') || ' ' || coalesce(address,'') || ' ' || coalesce(city,'') || ' ' || coalesce(province,'') || ' ' || coalesce(zip,'')));
CREATE INDEX IF NOT EXISTS "plant_fts_idx" ON "Plant" USING GIN (to_tsvector('italian', coalesce(code,'') || ' ' || coalesce(name,'') || ' ' || coalesce(type,'') || ' ' || coalesce("certificationStatus",'') || ' ' || coalesce(notes,'')));
CREATE INDEX IF NOT EXISTS "project_fts_idx" ON "Project" USING GIN (to_tsvector('italian', coalesce(code,'') || ' ' || coalesce(name,'') || ' ' || coalesce(description,'') || ' ' || coalesce("rupName",'') || ' ' || coalesce("dlName",'') || ' ' || coalesce("cigCode",'') || ' ' || coalesce("cupCode",'') || ' ' || coalesce(notes,'')));
CREATE INDEX IF NOT EXISTS "workorder_fts_idx" ON "WorkOrder" USING GIN (to_tsvector('italian', coalesce(code,'') || ' ' || coalesce(title,'') || ' ' || coalesce(description,'') || ' ' || coalesce(type,'') || ' ' || coalesce(cause,'')));
CREATE INDEX IF NOT EXISTS "report_fts_idx" ON "Report" USING GIN (to_tsvector('italian', coalesce(code,'') || ' ' || coalesce("workType",'') || ' ' || coalesce(cause,'') || ' ' || coalesce(description,'')));
CREATE INDEX IF NOT EXISTS "quote_fts_idx" ON "Quote" USING GIN (to_tsvector('italian', coalesce(number,'') || ' ' || coalesce(title,'') || ' ' || coalesce(description,'') || ' ' || coalesce(terms,'') || ' ' || coalesce("internalNotes",'')));
CREATE INDEX IF NOT EXISTS "invoice_fts_idx" ON "Invoice" USING GIN (to_tsvector('italian', coalesce(number,'') || ' ' || coalesce(series,'') || ' ' || coalesce("paymentMethod",'') || ' ' || coalesce(notes,'') || ' ' || coalesce("internalNotes",'') || ' ' || coalesce("sdiIdentifier",'')));
CREATE INDEX IF NOT EXISTS "purchaseorder_fts_idx" ON "PurchaseOrder" USING GIN (to_tsvector('italian', coalesce(number,'') || ' ' || coalesce(notes,'') || ' ' || coalesce("internalNotes",'')));
CREATE INDEX IF NOT EXISTS "purchaseinvoice_fts_idx" ON "PurchaseInvoice" USING GIN (to_tsvector('italian', coalesce(number,'') || ' ' || coalesce(series,'') || ' ' || coalesce(notes,'') || ' ' || coalesce("internalNotes",'')));
CREATE INDEX IF NOT EXISTS "material_fts_idx" ON "Material" USING GIN (to_tsvector('italian', coalesce(code,'') || ' ' || coalesce("metelCode",'') || ' ' || coalesce(barcode,'') || ' ' || coalesce(name,'') || ' ' || coalesce(brand,'') || ' ' || coalesce(category,'') || ' ' || coalesce(description,'')));
CREATE INDEX IF NOT EXISTS "vehicle_fts_idx" ON "Vehicle" USING GIN (to_tsvector('italian', coalesce(plate,'') || ' ' || coalesce(brand,'') || ' ' || coalesce(model,'') || ' ' || coalesce("fuelType",'') || ' ' || coalesce("insuranceCompany",'') || ' ' || coalesce("insurancePolicyNo",'') || ' ' || coalesce(notes,'')));
CREATE INDEX IF NOT EXISTS "maintenancecontract_fts_idx" ON "MaintenanceContract" USING GIN (to_tsvector('italian', coalesce(name,'') || ' ' || coalesce(description,'')));
CREATE INDEX IF NOT EXISTS "cashbookentry_fts_idx" ON "CashbookEntry" USING GIN (to_tsvector('italian', coalesce(category,'') || ' ' || coalesce(description,'') || ' ' || coalesce(counterpart,'') || ' ' || coalesce("documentRef",'') || ' ' || coalesce("paymentMethod",'') || ' ' || coalesce(notes,'')));
CREATE INDEX IF NOT EXISTS "incentiveapplication_fts_idx" ON "IncentiveApplication" USING GIN (to_tsvector('italian', coalesce(code,'') || ' ' || coalesce("workDescription",'') || ' ' || coalesce("bankTransferRef",'') || ' ' || coalesce("bankTransferDescription",'') || ' ' || coalesce("agenciaProtocol",'')));
CREATE INDEX IF NOT EXISTS "privacydocument_fts_idx" ON "PrivacyDocument" USING GIN (to_tsvector('italian', coalesce(audience,'') || ' ' || coalesce("subjectName",'') || ' ' || coalesce("subjectEmail",'') || ' ' || coalesce("subjectFiscalCode",'') || ' ' || coalesce("signerName",'')));
CREATE INDEX IF NOT EXISTS "conformitydeclaration_fts_idx" ON "ConformityDeclaration" USING GIN (to_tsvector('italian', coalesce(number,'') || ' ' || coalesce("rtName",'') || ' ' || coalesce("rtRegistrationNo",'') || ' ' || coalesce(notes,'')));
CREATE INDEX IF NOT EXISTS "assetacquisition_fts_idx" ON "AssetAcquisition" USING GIN (to_tsvector('italian', coalesce(code,'') || ' ' || coalesce(name,'') || ' ' || coalesce(description,'') || ' ' || coalesce(category,'') || ' ' || coalesce("serialNumber",'') || ' ' || coalesce(location,'') || ' ' || coalesce("invoiceRef",'') || ' ' || coalesce(notes,'')));
